SEX_MAP = {
    "Masculino": 1,
    "Feminino": 2,
}

MAR_MAP = {
    "Casado": 1,
    "Viúvo": 2,
    "Divorciado": 3,
    "Separado": 4,
    "Nunca casou": 5,
}

SCHL_MAP = {
    "Sem escolaridade": 1,
    "Fundamental incompleto": 8,
    "Fundamental completo": 12,
    "Ensino médio incompleto": 14,
    "Ensino médio completo": 16,
    "Alguma faculdade": 18,
    "Bacharelado": 21,
    "Mestrado": 22,
    "Doutorado": 24,
}

COW_MAP = {
    "Empregado empresa privada": 1,
    "Empregado governo": 2,
    "Autônomo": 3,
    "Trabalhador familiar": 4,
    "Desempregado": 9,
}

RACE_MAP = {
    "Branco": 1,
    "Negro": 2,
    "Indígena americano": 3,
    "Alasca nativo": 4,
    "Asiático": 5,
    "Havaiano / Pacífico": 6,
    "Outro": 7,
    "Múltiplas raças": 8,
    "Não informado": 9,
}

# POBP: aqui vai um conjunto útil e apresentável.
# Se depois você quiser expandir, é só adicionar mais itens.
POBP_MAP = {
    "Alabama": 1,
    "Alasca": 2,
    "Arizona": 4,
    "Arkansas": 5,
    "Califórnia": 6,
    "Colorado": 8,
    "Connecticut": 9,
    "Delaware": 10,
    "Distrito de Colúmbia": 11,
    "Flórida": 12,
    "Geórgia": 13,
    "Havaí": 15,
    "Idaho": 16,
    "Illinois": 17,
    "Indiana": 18,
    "Iowa": 19,
    "Kansas": 20,
    "Kentucky": 21,
    "Luisiana": 22,
    "Maine": 23,
    "Maryland": 24,
    "Massachusetts": 25,
    "Michigan": 26,
    "Minnesota": 27,
    "Mississippi": 28,
    "Missouri": 29,
    "Montana": 30,
    "Nebraska": 31,
    "Nevada": 32,
    "New Hampshire": 33,
    "New Jersey": 34,
    "Novo México": 35,
    "Nova York": 36,
    "Carolina do Norte": 37,
    "Dakota do Norte": 38,
    "Ohio": 39,
    "Oklahoma": 40,
    "Oregon": 41,
    "Pensilvânia": 42,
    "Rhode Island": 44,
    "Carolina do Sul": 45,
    "Dakota do Sul": 46,
    "Tennessee": 47,
    "Texas": 48,
    "Utah": 49,
    "Vermont": 50,
    "Virgínia": 51,
    "Washington": 53,
    "Virgínia Ocidental": 54,
    "Wisconsin": 55,
    "Wyoming": 56,
    "Porto Rico": 72,
    "México": 200,
    "Canadá": 150,
    "Brasil": 301,
    "China": 500,
    "Índia": 521,
    "Filipinas": 515,
    "Japão": 527,
    "Coreia": 528,
    "Vietnã": 555,
    "Alemanha": 453,
    "Reino Unido": 434,
    "Itália": 462,
    "Espanha": 465,
    "França": 421,
    "Outro país da América Latina": 250,
    "Outro país da Ásia": 599,
    "Outro país da Europa": 499,
    "Outro país da África": 699,
    "Outro país / território": 999,
}

# OCCP: usar grupos legíveis é muito melhor do que despejar centenas de códigos crus.
# Para apresentação, isso fica mais bonito e defensável.
OCCP_MAP = {
    "Gestão / Administração": 1000,
    "Negócios / Finanças": 1100,
    "Computação / TI": 1005,
    "Engenharia / Arquitetura": 1300,
    "Ciências / Pesquisa": 1600,
    "Saúde - Médicos": 3000,
    "Saúde - Enfermagem": 3255,
    "Saúde - Técnicos / Apoio": 3400,
    "Educação / Docência": 2300,
    "Jurídico": 2100,
    "Comunicação / Mídia / Artes": 2600,
    "Serviço social / Comunidade": 2000,
    "Proteção / Segurança": 3700,
    "Serviços de alimentação": 4000,
    "Limpeza / Manutenção": 4200,
    "Cuidado pessoal": 4300,
    "Vendas": 4700,
    "Atendimento administrativo / Escritório": 5700,
    "Agricultura / Pesca / Floresta": 6005,
    "Construção": 6200,
    "Instalação / Reparo / Manutenção": 7000,
    "Produção / Fábrica": 7700,
    "Transporte / Logística": 9000,
    "Militar": 9800,
}